version: '3.0'
services:
  admin:
    build: ./ms-atlpay-admin
    ports:
      - 48000:8000
  auth:
    build: ./ms-atlpay-authentication
    ports:
      - 45000:5000
    depends_on:
      - db
  master:
    build: ./ms-atlpay-master
    ports:
      - 46000:4000
    depends_on:
      - db
  merchant:
    build: ./ms-atlpay-merchant
    ports:
      - 47000:7000
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_MULTIPLE_DATABASES= "authDB","masterDB", "merchantDB", "adminDB"
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=arnab@agpaytech.co.uk
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
  nginx:
    image: nginx:latest
    ports: 
      - 8080:8080
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - admin
      - auth
      - master
      - merchant
      - db
volumes:
  database-data: {}